// 오늘결 13.0 · 실전 상담가 엔진
(()=>{
'use strict';
const $=s=>document.querySelector(s);
const HIST='todaygyeol.v13.used';
const WEEK=['일','월','화','수','목','금','토'];
const ko=(s='')=>String(s).replace(/[?？]+$/,'').trim();
function load(){try{return JSON.parse(localStorage.getItem(HIST)||'[]')}catch{return[]}}
function remember(s){const h=load();h.push(String(s));localStorage.setItem(HIST,JSON.stringify(h.slice(-40)))}
function norm(s){return String(s).replace(/[\s·,.:;!?"'“”‘’()]/g,'').replace(/오늘|이번|정말|조금|먼저|중요/g,'')}
function sim(a,b){a=norm(a);b=norm(b);if(!a||!b)return 0;const A=new Set([...a]),B=new Set([...b]);let n=0;A.forEach(x=>B.has(x)&&n++);return n/Math.max(A.size,B.size)}
function pick(arr,key=''){if(!arr?.length)return'';const h=load().slice(-16);let start=0;for(const c of String(key))start=(start*31+c.charCodeAt(0))>>>0;start%=arr.length;for(let k=0;k<arr.length;k++){const s=arr[(start+k)%arr.length];if(!h.some(x=>sim(x,s)>.72)){remember(s);return s}}const s=arr[start];remember(s);return s}
function prof(){try{return JSON.parse(localStorage.getItem('todaygyeol.v2.profile')||'null')}catch{return null}}
function ctx(){try{const p=prof();if(!p)return null;const ec=ecFromSolar(solarFromProfile(p),p);const cnt=countElements(ec),es=Object.entries(cnt).sort((a,b)=>b[1]-a[1]);return {p,ec,high:es[0]?.[0]||'',low:es.at(-1)?.[0]||'',dm:DAYMASTER?.[ec.getDayGan()]||null}}catch{return null}}
function today(){try{return dayInfo(todayYmd(),prof())}catch{return null}}

// 실제 상담에서 많이 나오는 질문을 의도+세부상황으로 분리
const RULES=[
 ['간식호의',/간식|과자|커피|음료|밥\s*사|선물|챙겨|사주고/],
 ['소개팅',/소개팅|첫\s*만남|소개\s*받/],['데이트',/데이트|둘이\s*만나|연인과\s*만나/],['고백',/고백|사귀자|마음\s*(전|말)|좋아한다고/],
 ['재회',/재회|전남친|전여친|다시\s*만나|헤어진/],['연락',/연락|카톡|문자|전화|DM|디엠/],['화해',/화해|사과|미안|서운|싸웠|갈등/],
 ['이직',/이직|퇴사|사표|직장\s*옮|회사\s*옮/],['승진협상',/승진|연봉|협상|고과|평가/],['면접지원',/면접|지원서|입사지원|취업/],
 ['직장대화',/팀장|상사|부장|과장|업무|보고|회의|프로젝트|담당/],['계약',/계약|서명|거래|매매|임대차|전세계약|월세계약/],
 ['투자',/주식|코인|투자|매수|매도|ETF|펀드/],['큰구매',/차\s*(살|사)|집\s*(살|사)|구매|살까|사도\s*될/],['창업',/창업|사업|가게|동업/],
 ['시험공부',/시험|공부|자격증|수능|공시/],['가족',/부모|엄마|아빠|가족|자녀|아이|형제|자매/],['이사',/이사|입주|전입/],['여행',/여행|출장|출발|비행/],
 ['건강',/병원|수술|치료|검사|약|건강|통증|아프/],['중요대화',/중요한\s*(말|이야기|얘기)|말\s*꺼|대화|설득|부탁|고민\s*말/],['약속',/약속|만날까|만남|시간\s*잡/]
];
function intent(q){for(const [n,r] of RULES)if(r.test(q))return n;return '일반';}
function whenQ(q){return /언제|몇\s*시|시간대|이번\s*주|다음\s*주|주말|이번\s*달|다음\s*달|날짜|요일/.test(q)}
function risk(i){return ['투자','건강','계약','큰구매','창업'].includes(i)}
function interText(di){if(!di)return '큰 관계 신호를 확인하지 못했습니다.'; if(di.inter?.type==='합')return '오늘은 내 일지와 그날 일지가 합으로 맞물립니다. 명리에서는 이런 날을 “사람이나 일이 서로 이어지기 쉬운 날”로 보지만, 관계가 자동으로 잘된다는 뜻은 아닙니다.'; if(di.inter?.type==='충')return '오늘은 내 일지와 그날 일지가 충입니다. 이런 날은 멈춰 있기보다 움직임이 생기기 쉽고, 말이나 일정이 예상보다 빨리 바뀔 수 있다고 봅니다.'; return '오늘은 내 일지와 일진 사이에 큰 합·충이 없습니다. 이런 날은 운의 힘보다 내가 어떻게 준비했고 상대가 어떻게 반응하느냐가 더 중요합니다.'}
function relText(rel){return ({지원:'천간 관계는 지원 쪽입니다. 혼자 밀어붙이기보다 정보를 더 듣거나 도움을 받는 방식이 잘 맞습니다.',표현:'천간 관계는 표현 쪽입니다. 생각만 하기보다 말·신청·제안처럼 밖으로 꺼내는 행동이 살아납니다.',관리:'천간 관계는 관리 쪽입니다. 돈, 약속, 조건, 일정처럼 “정리해야 결과가 남는 것”을 챙기기 좋습니다.',압박:'천간 관계는 압박 쪽입니다. 책임감이나 조급함이 커질 수 있어, 해야 한다는 마음과 지금 해야 한다는 판단을 나눠볼 필요가 있습니다.',동질:'천간 관계는 동질 쪽입니다. 내 방식대로 움직이기 쉬운 대신 다른 사람의 속도를 놓치지 않는 게 중요합니다.'}[rel]||'천간 관계는 한쪽으로 강하게 치우치지 않아 현실 조건이 우선입니다.');}

const COUNSEL={
 간식호의:{title:'가볍게 해도 좋아요', opening:q=>`이건 거창한 호의로 만들 필요가 없습니다. ${/동료/.test(q)?'동료 사이에서는 특히':'관계 초반에는'} 작은 친절이 부담으로 느껴지지 않는지가 핵심이에요.`, practical:q=>/과자|간식/.test(q)?'과자 한 봉지를 따로 “선물”처럼 주기보다 “이거 같이 드실래요?” 하고 공동 간식처럼 꺼내세요. 상대가 바빠 보이면 책상에 오래 붙잡아 두지 말고 5~10분만 이야기하고 먼저 마무리하는 편이 좋습니다.':'커피나 음료라면 취향을 단정하지 말고 “커피 드세요? 아니면 다른 거 드실래요?”처럼 선택권을 주세요.', example:'예를 들어 오후에 일이 잠깐 끊기는 시간이 보이면 “저 잠깐 간식 먹으려고 하는데 같이 드실래요?” 정도면 충분합니다. 상대가 바로 업무 이야기로 돌아가면 그 신호를 존중하고, 대화가 자연스럽게 이어지면 그때 조금 더 이야기하세요.', differ:'상대가 마감 직전이거나 표정이 굳어 있고 계속 화면을 보고 있다면 오늘 운이 좋아도 그 순간은 피하는 게 맞습니다.'},
 소개팅:{title:'약속을 잡아볼 만해요',opening:()=>`소개팅은 좋은 날 하나보다 “첫 만남을 얼마나 편하게 만들 수 있느냐”가 더 중요합니다. 그래도 날짜 후보가 여러 개라면 명리 흐름을 동점 결정 기준으로 쓰면 꽤 실용적이에요.`,practical:()=>`첫 만남은 1~2시간 안에 끝낼 수 있는 카페나 식사 한 곳 정도가 좋습니다. 멀리 이동하는 코스, 영화처럼 대화가 끊기는 일정, 너무 늦은 시간은 첫 만남에선 굳이 넣지 마세요.`,example:'약속을 잡을 때는 “언제 시간 돼요?”보다 “목요일 저녁이나 토요일 오후 중 편한 쪽 있어요?”처럼 두 가지 선택지를 주세요. 상대가 고를 수 있어야 부담이 줄고, 답도 빨리 옵니다.',differ:'상대가 이미 특정 요일을 편해 한다면 그 현실 조건이 1순위입니다. 명리상 2순위 날짜라도 둘 다 편한 날이 실제로는 더 좋은 선택입니다.'},
 데이트:{title:'둘의 컨디션을 먼저 맞춰보세요',opening:()=>`데이트는 “특별한 걸 해야 좋은 날”로 보지 않는 게 좋습니다. 둘이 피곤하지 않고, 대화를 끊지 않아도 되는 일정이면 이미 절반은 맞습니다.`,practical:()=>`한두 곳만 잡고 중간에 쉬는 시간을 남겨두세요. 최근 서로 바빴다면 전시·쇼핑처럼 계속 움직이는 코스보다 식사 후 산책처럼 대화할 틈이 있는 일정이 낫습니다.`,example:'예를 들어 상대가 이번 주 야근이 많았다면 토요일 오전부터 하루 종일 보는 것보다 오후 4~5시에 만나 저녁까지 보내는 편이 훨씬 편할 수 있습니다.',differ:'최근 다툰 직후라면 데이트를 관계 해결의 “시험대”로 만들지 마세요. 짧게 만나 분위기를 회복하는 게 먼저입니다.'},
 고백:{title:'마음은 말하되 답을 밀어붙이진 마세요',opening:()=>`고백은 날짜보다 관계의 현재 온도가 먼저입니다. 둘이 따로 만나는 일이 자연스럽고, 상대도 먼저 연락하거나 시간을 내는지부터 보세요.`,practical:()=>`감정의 크기를 증명하는 긴 말보다 “나는 요즘 너를 친구 이상으로 생각하고 있어. 너는 우리 관계를 어떻게 느껴?”처럼 내 마음과 질문을 한 번씩만 꺼내는 편이 좋습니다.`,example:'좋은 분위기에서 헤어지기 직전 갑자기 몰아치기보다, 둘이 충분히 이야기한 뒤 조용한 순간에 1~2문장으로 꺼내세요. 상대가 바로 답하지 않아도 괜찮다는 여지를 주는 게 중요합니다.',differ:'최근 답장이 짧아졌거나 만남을 계속 미루는 상태라면 고백으로 상황을 뒤집으려 하기보다, 먼저 관계 온도를 확인하는 대화를 권합니다.'},
 재회:{title:'재회보다 먼저 “다시 만나도 달라질 게 있는지”를 보세요',opening:()=>`헤어진 사람과 다시 연락하고 싶을 때는 그리움과 재회 가능성을 구분해야 합니다. 다시 만났을 때 예전 문제가 그대로라면 재회 자체가 답은 아니에요.`,practical:()=>`연락한다면 감정 장문보다 짧은 안부가 낫습니다. “잘 지내? 문득 생각나서 안부 궁금했어.” 정도로 보내고, 상대 반응이 없거나 차갑다면 추가 메시지는 멈추세요.`,example:'상대가 대화를 이어오면 그때 “다시 사귀자”부터 말하지 말고, 헤어진 뒤 서로 무엇이 달라졌는지를 먼저 확인하세요.',differ:'폭언·폭력·통제처럼 안전을 해친 관계였다면 재회운보다 안전과 거리두기가 우선입니다.'},
 연락:{title:'연락은 짧게 한 번이 좋아요',opening:()=>`연락은 보내는 시간보다 “상대가 답하기 쉬운 내용인가”가 더 중요합니다. 긴 설명이나 감정 확인부터 시작하면 상대가 답을 미루기 쉬워요.`,practical:()=>`안부 한 문장에 가벼운 질문 하나 정도면 충분합니다. 답이 늦더라도 같은 날 추가 메시지를 여러 번 보내지 마세요.`,example:'오랜만이라면 “잘 지냈어? 지난번에 네가 말한 ○○ 생각나서. 요즘은 어때?”처럼 연락한 이유를 한 줄 넣으면 덜 뜬금없습니다.',differ:'업무시간에 바쁜 사람이나 교대근무자는 “좋은 시간”보다 상대의 생활패턴을 따르는 게 맞습니다.'},
 화해:{title:'오늘 풀려면 한 사건만 이야기하세요',opening:()=>`화해할 때 가장 많이 꼬이는 건 과거 사건을 한꺼번에 다 꺼내는 겁니다. 이번에 풀 문제 하나만 정해야 대화가 앞으로 갑니다.`,practical:()=>`사실 → 내 감정 → 다음에 원하는 행동 순서로 말해보세요. “어제 약속이 바뀌었는데 연락이 늦어서 서운했어. 다음엔 바뀌면 먼저 알려줬으면 해.” 정도면 충분합니다.`,example:'사과해야 한다면 “그럴 의도는 아니었어”부터 붙이지 마세요. “그 말이 상처였겠네. 그 부분은 내가 미안해.”라고 인정한 뒤 해명은 상대가 들을 준비가 됐을 때 하세요.',differ:'둘 중 한 사람이 아직 목소리가 커질 정도로 화가 나 있다면 오늘 결론까지 내지 말고, 다시 이야기할 시간을 정하는 데까지만 가는 게 낫습니다.'},
 직장대화:{title:'말보다 자료를 하나 들고 가세요',opening:()=>`직장 대화는 운보다 상대가 판단할 수 있는 정보가 있어야 풀립니다. 특히 상사에게는 “힘들다”보다 “무엇을 결정해 달라”가 보여야 해요.`,practical:()=>`메모 세 줄이면 됩니다. ① 현재 상황 ② 문제가 되는 부분 ③ 내가 원하는 결정. 업무량 문제라면 A·B·C가 겹친다는 사실과 우선순위를 물어보는 식입니다.`,example:'“지금 A와 B 마감이 이번 주에 겹칩니다. A를 먼저 하면 B는 금요일까지 늦어집니다. 어느 쪽을 우선하면 될까요?”라고 말하면 상대도 바로 결정할 수 있습니다.',differ:'단순 불만이 아니라 괴롭힘·안전·법적 문제가 얽혔다면 구두 상담만 하지 말고 기록과 공식 절차를 함께 챙겨야 합니다.'},
 이직:{title:'옮길 수는 있지만, 조건표부터 만드세요',opening:()=>`이직은 운이 좋다는 이유로 회사부터 그만두는 문제가 아닙니다. 새 자리가 지금보다 무엇을 주고 무엇을 가져가는지 표로 놓고 봐야 합니다.`,practical:()=>`연봉, 실제 역할, 상사, 근무시간, 출퇴근, 2년 뒤 경력가치를 같은 기준으로 현재 회사와 비교하세요. 오퍼레터가 확정되기 전 사표부터 내는 건 피하세요.`,example:'연봉이 10% 오르더라도 출퇴근이 하루 2시간 늘고 직무가 경력에 남지 않는다면 체감 조건은 나빠질 수 있습니다. 반대로 연봉 차이가 작아도 책임 범위와 성장성이 커지면 장기적으로는 다른 선택이 됩니다.',differ:'현재 회사에서 역할 변경이나 승진으로 같은 문제를 해결할 수 있다면 외부 이직과 내부 이동을 같이 비교하세요.'},
 승진협상:{title:'“열심히 했다”보다 증거 3개가 필요해요',opening:()=>`승진이나 연봉협상은 타이밍도 보지만, 결국 회사가 확인할 수 있는 성과가 있어야 합니다.`,practical:()=>`지난 6~12개월에서 비용을 줄인 일, 시간을 줄인 일, 책임이 커진 일 중 세 가지를 숫자로 정리하세요. 원하는 조건도 최소·목표·대안 세 단계로 준비하는 게 좋습니다.`,example:'“매출을 올렸습니다”보다 “기존 고객 재구매율을 18%에서 25%로 높였습니다”처럼 결과가 보이는 말이 협상에서 훨씬 강합니다.',differ:'직함만 올라가고 사람·예산·권한은 그대로인데 책임만 늘어난다면 승진 자체가 좋은 조건인지 다시 봐야 합니다.'},
 면접지원:{title:'지원은 해보세요. 대신 사례를 준비하세요',opening:()=>`면접은 좋은 날보다 “내가 어떤 사람인지 증명할 사례가 준비됐는가”가 더 중요합니다.`,practical:()=>`성공 사례 2개와 실패 후 고친 사례 1개를 준비하세요. 상황, 내가 한 행동, 숫자로 남은 결과를 짧게 정리하면 질문이 달라져도 응용할 수 있습니다.`,example:'예를 들어 “협업 잘합니다” 대신 “개발·영업 일정이 충돌했을 때 우선순위 표를 만들어 마감 지연을 2주에서 3일로 줄였다”는 식으로 말하세요.',differ:'지원하려는 직무가 현재 경력과 크게 다르면 “왜 바꾸는가”보다 기존 경험 중 무엇을 그대로 가져갈 수 있는지를 연결해 보여주는 게 중요합니다.'},
 계약:{title:'사주는 참고만, 계약서는 실제로 읽어야 해요',opening:()=>`계약은 길일보다 문구가 먼저입니다. 오늘 흐름이 아무리 좋아도 불리한 계약은 좋은 계약이 되지 않습니다.`,practical:()=>`금액, 계약기간, 중도해지, 위약금, 자동갱신, 책임범위, 특약을 체크하세요. 말로 들은 조건이 문서에 없으면 상대에게 적어달라고 요청해야 합니다.`,example:'렌탈이라면 월요금만 보지 말고 의무사용기간과 중도해지금까지 계산하고, 임대차라면 보증금 반환 조건과 특약을 확인하는 식입니다.',differ:'상대가 “오늘 안 하면 조건이 사라진다”고 재촉할수록 오히려 바로 서명하지 말고 확인 시간을 확보하세요.'},
 투자:{title:'투자는 사주로 매수·매도 결정을 하지 마세요',opening:()=>`재물운과 투자수익은 같은 말이 아닙니다. 주가나 코인 가격을 사주로 예측할 수는 없습니다.`,practical:()=>`매수 이유, 손실 한도, 투자기간, 포트폴리오 비중을 먼저 적으세요. 특히 생활비·대출금·비상금은 투자 판단에서 빼는 게 기본입니다.`,example:'“오를 것 같다” 대신 “실적이 이 수준을 유지하고 가격이 이 범위면 산다, 이 조건이 깨지면 줄인다”처럼 내 판단이 틀렸음을 인정할 기준을 미리 정하세요.',differ:'단기 급등을 보고 마음이 급해졌다면 운이 아니라 과열 심리일 가능성을 먼저 의심해야 합니다.'},
 큰구매:{title:'사고 싶다면 1년 총비용으로 보세요',opening:()=>`큰 구매는 오늘 기분보다 유지비가 결정합니다. 차·집·고가 제품은 가격표만 보면 실제 부담을 놓치기 쉽습니다.`,practical:()=>`구매가+보험+세금+수리·관리비+대출이자를 1년 기준으로 적어보세요. 하루 뒤 다시 봐도 같은 선택인지 확인하는 것도 좋습니다.`,example:'차가 3천만원이라도 보험·주차·유류·정비가 매달 수십만원이면 내 현금흐름에는 전혀 다른 가격입니다.',differ:'업무나 가족 사정 때문에 반드시 필요한 구매라면 “살까 말까”보다 예산 안에서 어떤 선택이 가장 안전한지를 보는 쪽이 맞습니다.'},
 창업:{title:'시작 날짜보다 고객 확인이 먼저예요',opening:()=>`창업운이 있다고 해도 고객이 돈을 내지 않으면 사업은 굴러가지 않습니다. 명리는 속도 조절에 쓰고, 사업성은 숫자로 확인해야 합니다.`,practical:()=>`임대차나 큰 장비를 사기 전에 2~4주짜리 작은 판매 테스트를 해보세요. 월 고정비, 손익분기 매출, 최소 6개월 운영자금을 계산하는 게 먼저입니다.`,example:'카페라면 “이 동네에 카페가 많다”보다 평일·주말 유동인구와 예상 객단가로 하루 몇 명이 와야 손익분기인지 계산해야 합니다.',differ:'동업이라면 친분보다 지분, 역할, 의사결정권, 돈을 더 넣는 조건, 그만둘 때 절차를 문서로 정하세요.'},
 시험공부:{title:'새로 늘리기보다 틀리는 이유를 줄이세요',opening:()=>`시험을 앞두고는 공부량을 늘리는 것보다 실수 패턴을 줄이는 게 점수에 더 직접적입니다.`,practical:()=>`기출을 실제 시간으로 풀고 오답을 지식 부족·시간 부족·실수로 나누세요. 유형이 보이면 다음 공부가 훨씬 짧아집니다.`,example:'3시간이 있다면 새 강의 3개를 보는 것보다 기출 30문제를 풀고 틀린 8문제의 이유를 적는 식이 효율적입니다.',differ:'시험 하루 전이라면 새로운 범위를 넓히는 것보다 수면, 준비물, 이동시간을 챙기는 편이 실제 결과에 더 도움이 됩니다.'},
 가족:{title:'가족 문제는 이번에 풀 한 가지만 정하세요',opening:()=>`가족 대화는 오래된 기억이 섞이기 쉬워서 주제를 넓히면 금방 “예전에도 그랬잖아”로 갑니다.`,practical:()=>`이번 대화에서 바꾸고 싶은 행동 하나만 정하세요. 돈 문제면 필요한 금액·기간·각자 가능한 부담을 숫자로 놓고 이야기하는 편이 낫습니다.`,example:'“왜 나만 늘 해야 해?”보다 “이번 달 병원비가 40만원인데 나는 20만원까지 가능해. 나머지는 어떻게 나누면 좋을까?”라고 말하면 논점이 분명해집니다.',differ:'폭력이나 학대처럼 안전 문제가 있다면 가족 화합보다 외부 도움과 안전 확보가 우선입니다.'},
 이사:{title:'길일은 마지막 동점 기준으로 쓰세요',opening:()=>`이사는 날짜의 길흉보다 잔금과 입주, 엘리베이터, 전입신고 같은 실제 조건이 먼저입니다.`,practical:()=>`후보 날짜마다 비용, 휴가 사용, 이삿짐센터 가능 여부, 교통, 관리사무소 시간을 비교하세요. 조건이 비슷할 때 명리상 더 부드러운 날을 고르는 게 합리적입니다.`,example:'오전 길시가 나와도 아파트 엘리베이터 예약이 오후뿐이면 억지로 시간을 맞출 이유는 없습니다. 현실 일정 안에서 가장 좋은 시간을 다시 고르면 됩니다.',differ:'잔금일과 이사일을 분리할 수 있다면 계약·금전 판단과 실제 이동 시간을 따로 잡는 것도 방법입니다.'},
 여행:{title:'좋은 시간보다 무리 없는 동선이 우선이에요',opening:()=>`여행은 출발운보다 교통·날씨·체력이 훨씬 크게 좌우합니다.`,practical:()=>`핵심 일정 하나, 선택 일정 두 개 정도로 나누고 환승과 귀가시간을 넉넉히 잡으세요.`,example:'비행기가 오후라면 오전부터 관광을 꽉 채우는 것보다 체크아웃 후 공항 이동 변수를 남겨두는 편이 여행 전체를 편하게 만듭니다.',differ:'출장처럼 중요한 발표가 있다면 이동 직후 바로 회의하는 일정은 피하고 여유 시간을 확보하세요.'},
 건강:{title:'건강은 명리가 아니라 의료정보가 먼저입니다',opening:()=>`건강 질문은 사주로 좋고 나쁨을 판단하지 않겠습니다. 증상, 검사, 담당 의료진의 설명이 기준입니다.`,practical:()=>`치료나 수술 날짜를 고른다면 응급성, 담당의 일정, 병원 시스템, 회복에 필요한 휴가를 먼저 확인하세요.`,example:'명리상 좋은 날이라도 담당 전문의가 없거나 회복 지원을 받을 수 없는 날이면 현실적으로는 좋은 날짜가 아닙니다.',differ:'통증·호흡곤란·출혈처럼 급한 증상이 있으면 날짜를 고르느라 진료를 미루지 마세요.'},
 중요대화:{title:'핵심 한 가지부터 꺼내세요',opening:()=>`중요한 말일수록 다 설명하려고 하면 상대가 무엇에 답해야 하는지 놓칩니다.`,practical:()=>`결론 하나, 근거 두 개, 상대에게 묻고 싶은 것 하나만 준비하세요. 민감한 이야기는 메시지 장문보다 시간을 잡고 직접 말하는 편이 오해가 적습니다.`,example:'“우리 관계에 대해 할 말이 많아”보다 “요즘 연락 간격이 길어져서 나는 조금 멀어진 느낌이 들어. 너는 요즘 우리 관계를 어떻게 느껴?”처럼 하나의 변화부터 짚으세요.',differ:'상대가 회의 직전, 운전 중, 잠들기 직전이라면 내용이 아무리 중요해도 그 순간은 피하세요.'},
 약속:{title:'두 가지 시간만 제안해보세요',opening:()=>`약속을 잡는 건 운보다 상대가 답하기 쉽게 만드는 게 먼저입니다.`,practical:()=>`“언제 돼?”라고 넓게 묻기보다 내가 가능한 두세 시간을 주세요. 첫 만남이면 너무 늦거나 이동이 긴 시간은 피하는 편이 좋습니다.`,example:'“목요일 7시나 토요일 3시 중 편한 쪽 있어?”처럼 물으면 상대도 일정표를 오래 뒤질 필요가 없습니다.',differ:'상대가 육아·교대근무처럼 시간 제약이 크다면 내 좋은 시간보다 상대의 가능한 시간을 우선하세요.'},
 일반:{title:'작게 해보고 반응을 보세요',opening:()=>`이건 거창하게 운세로 자를 질문은 아닙니다. 되돌리기 쉬운 선택인지부터 보면 답이 빨라져요.`,practical:()=>`되돌리기 쉬운 일은 작은 범위로 해보고, 되돌리기 어려운 일은 비용·시간·관계 영향을 한 번 더 확인하세요.`,example:'연락은 한 번 보내고 기다리고, 구매는 하루 뒤 다시 보고, 부탁은 상대가 거절해도 괜찮은 방식으로 말하는 식입니다.',differ:'돈·건강·법률처럼 결과가 큰 문제라면 사주보다 객관적 자료와 전문가 판단을 앞에 두세요.'}
};

function conclusion(i,di){const c=COUNSEL[i]||COUNSEL.일반;if(risk(i))return c.title;if(di?.inter?.type==='충'&&['고백','화해','중요대화'].includes(i))return '말은 해도 되지만 결론을 서두르진 마세요';if(di?.inter?.type==='합'&&['소개팅','데이트','고백','연락','간식호의','약속'].includes(i))return c.title;return c.title;}
function personal(c,di,i){if(!c||!di)return'';const dm=c.dm?.name||ganzhiKo(c.ec.getDayGan());const lines=[];lines.push(`${c.p.name||'당신'}님은 ${dm} 일간이고, 원국에서는 ${c.high} 기운을 비교적 익숙하게 쓰는 편입니다. ${c.low} 기운은 상대적으로 적어서, 중요한 선택에서 늘 하던 방식만 반복하면 한쪽으로 치우칠 수 있어요.`); if(['간식호의','소개팅','데이트','고백','재회','연락','화해','중요대화','약속'].includes(i))lines.push(c.high==='토'?'관계에서도 책임지고 정리하려는 마음이 먼저 나올 수 있는데, 상대는 해결보다 공감이나 여유를 원할 때가 있습니다.':'관계에서는 내 속도보다 상대의 반응을 한 박자 더 확인하는 게 좋습니다.'); else if(['이직','승진협상','직장대화','면접지원'].includes(i))lines.push(c.high==='금'?'일에서는 기준과 결과를 분명히 잡는 강점이 있습니다. 다만 사람을 설득할 때는 정답만 제시하기보다 선택 이유를 설명하면 훨씬 잘 먹힙니다.':'일에서는 타고난 방식에만 기대기보다 숫자·기한·역할을 눈에 보이게 정리하면 운을 현실 성과로 바꾸기 쉽습니다.');return lines.join(' ')}
function caseHeading(i){return ({간식호의:'이 상황이라면 이렇게 해보세요',소개팅:'약속을 잡는 장면으로 보면',데이트:'실제 데이트로 옮기면',고백:'말을 꺼내는 순간은 이렇게',재회:'연락을 한다면 여기까지만',연락:'메시지는 이 정도면 충분해요',화해:'실제로 말할 때는',직장대화:'회사에서는 이렇게 말하면 됩니다',이직:'조건표에는 이걸 적으세요',승진협상:'협상 자리에서는',면접지원:'면접에서는 이렇게 바꿔 말하세요',계약:'계약서에서 먼저 찾을 항목',투자:'투자라면 이 기준부터',큰구매:'계산은 이렇게 해보세요',창업:'사업으로 옮기기 전에',시험공부:'오늘 공부한다면',가족:'가족에게 말할 때는',이사:'이사 후보를 고를 때는',여행:'일정을 짤 때는',건강:'날짜를 고르기 전',중요대화:'말문은 이렇게 열어보세요',약속:'약속 메시지는 이렇게',일반:'실제로는 이렇게 해보세요'}[i]||'실제로는 이렇게 해보세요')}
function conditionHeading(i){return ['소개팅','데이트','고백','재회','연락','화해','간식호의'].includes(i)?'다만 이런 경우면 이야기가 달라져요':'여기서 한 가지는 꼭 구분하세요'}
function answer(q){const p=prof();if(!p)return alert('내 사주를 먼저 등록하세요.');if(whenQ(q))return schedule(q,intent(q));const i=intent(q),di=today(),c=ctx(),x=COUNSEL[i]||COUNSEL.일반;const basis=`${interText(di)} ${relText(di?.rel)}`;const whyPersonal=personal(c,di,i);const title=conclusion(i,di);const qshort=ko(q);const prefaces=[`${qshort}라고 물으셨죠. 제 답은 <b>${title}</b> 쪽입니다.`,`${qshort}. 이 질문은 결론부터 말씀드리면 <b>${title}</b>라고 보겠습니다.`,`이 질문은 애매하게 돌리지 않을게요. <b>${title}</b> 쪽입니다.`];return `<div class="v13-consult"><span class="badge">${i} 상담</span><h2 class="v13-verdict">${pick(prefaces,q+i)}</h2><p class="v13-opening">${x.opening(q)}</p><section class="v13-block"><h3>현실에서는 이걸 먼저 봅니다</h3><p>${x.practical(q)}</p></section><section class="v13-block example"><h3>${caseHeading(i)}</h3><p>${x.example}</p></section><section class="v13-block"><h3>사주 흐름을 겹쳐보면</h3><p>${whyPersonal}</p><p>${basis}</p></section><section class="v13-block condition"><h3>${conditionHeading(i)}</h3><p>${x.differ}</p></section><div class="v13-final"><b>그래서 제 선택은</b><p>${finalAction(i,di)}</p></div><details><summary>왜 이렇게 봤는지 계산 근거</summary><p class="small">오늘 일진 ${di?ganzhiKo(di.ec.getDay()):'-'} · 내 일지와 ${di?.inter?.type||'평'} · 일간 관계 ${di?.rel||'-'}<br>내 일간 ${c?ganzhiKo(c.ec.getDayGan()):'-'} · 강한 오행 ${c?.high||'-'} · 상대적으로 적은 오행 ${c?.low||'-'}</p><p class="small muted">명리 관계는 전통 해석의 참고 자료이며 실제 성공률이나 사건 발생 확률이 아닙니다.</p></details></div>`}
function finalAction(i,di){const map={간식호의:'부담 없는 작은 호의로 시작하고, 상대가 대화를 이어오면 그때 조금 더 머무세요. 호의를 관계의 시험으로 만들지는 마세요.',소개팅:'약속을 잡아도 좋습니다. 상대에게 두 가지 시간 선택지를 주고, 첫 만남은 짧고 편하게 끝낼 수 있게 만드세요.',데이트:'일정을 많이 넣기보다 둘이 편하게 이야기할 시간이 남는 코스로 잡으세요.',고백:di?.inter?.type==='충'?'마음은 표현할 수 있지만 오늘 바로 관계의 결론까지 요구하지는 마세요.':'마음을 말해도 좋습니다. 다만 내 마음 한 문장과 상대의 생각을 묻는 질문 한 문장으로 끝내세요.',재회:'안부 연락 한 번까지는 가능하지만, 상대 반응이 없으면 추가 연락으로 밀어붙이지 마세요.',연락:'짧게 한 번 보내고 기다리세요. 답장이 관계의 실제 정보를 줍니다.',화해:'최근 사건 하나만 다루고, 사과할 부분과 다음에 바라는 행동을 분리해서 말하세요.',직장대화:'문제·영향·원하는 결정을 세 줄로 정리해서 이야기하세요.',이직:'오늘은 비교하고 확인하는 데 쓰고, 오퍼가 문서로 확정되기 전에는 퇴사를 먼저 확정하지 마세요.',승진협상:'성과 3개와 원하는 조건 범위를 준비한 뒤 이야기하세요.',면접지원:'지원은 해보세요. 대신 일반적인 장점보다 직무와 연결되는 실제 사례 3개를 준비하세요.',계약:'좋은 날 여부와 별개로 계약서를 읽고 불리한 조건을 수정할 수 있을 때만 진행하세요.',투자:'사주로 매수·매도하지 마세요. 손실 한도와 투자 근거가 먼저입니다.',큰구매:'하루 총감정이 아니라 1년 총비용으로 보고 결정하세요.',창업:'계약보다 작은 판매 테스트를 먼저 하고 숫자가 맞는지 확인하세요.',시험공부:'오늘은 새 범위를 넓히기보다 오답과 시간관리 약점을 줄이는 데 집중하세요.',가족:'이번 대화에서 해결할 주제 하나만 정하고 숫자나 행동으로 말하세요.',이사:'현실 일정이 비슷한 후보끼리만 명리 기준으로 비교하세요.',여행:'동선을 줄이고 변수를 흡수할 여유 시간을 남겨두세요.',건강:'의료진 판단과 실제 치료 조건을 우선하세요.',중요대화:'핵심 하나만 꺼내고 상대의 답을 들은 뒤 다음 이야기를 이어가세요.',약속:'가능한 시간 두 개를 제안하고 상대가 고르게 하세요.',일반:'되돌리기 쉬운 작은 행동으로 먼저 확인하고, 큰 결정은 현실 조건을 한 번 더 보세요.'};return map[i]||map.일반}

function range(q){const n=new Date();n.setHours(0,0,0,0);let s=new Date(n),e=new Date(n),label='이번 주';const dow=n.getDay(); if(/다음\s*주/.test(q)){s.setDate(n.getDate()+(7-dow)+(dow===0?0:0));if(dow===0)s.setDate(n.getDate()+1);e=new Date(s);e.setDate(s.getDate()+6);label='다음 주'}else if(/이번\s*주말|주말/.test(q)){const sat=(6-dow+7)%7;s.setDate(n.getDate()+sat);e=new Date(s);e.setDate(s.getDate()+1);label='이번 주말'}else if(/다음\s*달/.test(q)){s=new Date(n.getFullYear(),n.getMonth()+1,1);e=new Date(n.getFullYear(),n.getMonth()+2,0);label='다음 달'}else if(/이번\s*달/.test(q)){s=new Date(n);e=new Date(n.getFullYear(),n.getMonth()+1,0);label='이번 달'}else{e.setDate(n.getDate()+(7-dow));if(dow===0)e=new Date(n);label='이번 주'}return{s,e,label}}
function iso(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function add(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}
function timeWindows(i){if(['소개팅','데이트','고백','약속','재회'].includes(i))return[[13,15],[15,17],[17,19],[19,21]];if(['직장대화','승진협상','면접지원','계약'].includes(i))return[[9,11],[11,13],[13,15],[15,17]];if(i==='시험공부')return[[7,9],[9,11],[13,15],[15,17]];if(['이사','여행'].includes(i))return[[7,9],[9,11],[11,13],[13,15]];return[[9,11],[11,13],[15,17],[17,19],[19,21]]}
function tInfo(ds,h,p){try{const {y,m,d}=ymd(ds),s=Solar.fromYmdHms(y,m,d,h,0,0),ec=s.getLunar().getEightChar();try{ec.setSect(Number(p.sect||2))}catch{}const n=ecFromSolar(solarFromProfile(p),p);const a=interaction(n.getDayZhi(),ec.getTimeZhi()),b=interaction(ec.getDayZhi(),ec.getTimeZhi()),r=relation(n.getDayGan(),ec.getTimeGan());let sc=65+(a.type==='합'?10:a.type==='충'?-12:0)+(b.type==='합'?5:b.type==='충'?-6:0)+({지원:5,표현:4,동질:2,관리:2,압박:-4}[r]||0);return{h,a,b,r,sc,ec}}catch{return{h,a:{type:'평'},b:{type:'평'},r:'중립',sc:55}}}
function purpose(i){if(['소개팅','데이트','고백','약속','재회'].includes(i))return'소개팅·만남';if(['계약','투자','큰구매','창업'].includes(i))return'계약·거래';if(['이사','여행'].includes(i))return'이사·이동';if(['시험공부','면접지원'].includes(i))return'공부·시험 준비';return'중요한 대화'}
function scoreDay(ds,p,i){const di=dayInfo(ds,p);let s=purposeScore(di,purpose(i));const tw=timeWindows(i).map(([a,b])=>({...tInfo(ds,a,p),a,b})).sort((x,y)=>y.sc-x.sc)[0];s+=Math.round((tw.sc-60)*.4);return{di,tw,s}}
function dayName(d){return `${d.getMonth()+1}월 ${d.getDate()}일 ${WEEK[d.getDay()]}요일`}
function hour(a,b){return `${String(a).padStart(2,'0')}:00~${String(b).padStart(2,'0')}:00`}
function reasonDate(x,i){const a=[];if(x.di.inter.type==='합')a.push('내 일지와 그날 일지가 합이라 연결·만남 쪽 신호를 우선 반영했습니다');else if(x.di.inter.type==='충')a.push('내 일지와 그날 일지가 충이라 변화성은 있지만 1순위로는 감점했습니다');else a.push('내 일지와 그날 일지에 큰 합·충이 없어 일정이 비교적 담백합니다');if(x.di.rel==='지원')a.push('그날 천간이 내 일간을 돕는 관계라 부담을 덜고 정보를 받는 쪽이 좋습니다');if(x.di.rel==='표현')a.push('그날 천간이 표현 관계라 말·제안·만남처럼 밖으로 움직이는 질문과 잘 맞습니다');if(x.di.rel==='관리')a.push('그날 천간이 관리 관계라 약속과 조건을 정리하기 좋습니다');const yi=translateActs(x.di.yi||[],3);if(yi?.length)a.push(`전통력의 좋은 활동에도 ${yi.join('·')}가 포함됩니다`);return a.slice(0,3).join('. ')+'.'}
function reasonTime(x){const a=[];if(x.tw.a.type==='합')a.push('이 시간의 시지가 내 일지와 합으로 이어집니다');else if(x.tw.a.type==='충')a.push('이 시간의 시지가 내 일지와 충이라 감점 요소가 있습니다');else a.push('이 시간 시지가 내 일지와 크게 부딪히지 않습니다');if(x.tw.b.type==='합')a.push('그날 일지와 시간 지지도 합으로 이어집니다');else if(x.tw.b.type==='충')a.push('그날 일지와 시간 지지에 충이 있어 너무 급하게 결론내리는 시간으로는 덜 추천합니다');if(x.tw.r==='지원')a.push('시간 천간도 내 일간을 돕는 관계입니다');if(x.tw.r==='표현')a.push('시간 천간은 말과 행동을 꺼내는 관계입니다');return a.slice(0,3).join('. ')+'.'}
function schedule(q,i){const p=prof(),rg=range(q),rows=[];for(let d=new Date(rg.s);d<=rg.e;d=add(d,1)){try{const ds=iso(d),x=scoreDay(ds,p,i);rows.push({d:new Date(d),ds,...x})}catch{}}rows.sort((a,b)=>b.s-a.s);const top=rows.slice(0,3),best=top[0],worst=[...rows].sort((a,b)=>a.s-b.s)[0];if(!best)return'<p>후보 날짜를 계산하지 못했습니다.</p>';const intentName=({소개팅:'소개팅',데이트:'데이트',고백:'고백',약속:'약속',직장대화:'중요한 업무 대화',면접지원:'면접',계약:'계약',이사:'이사',여행:'여행'}[i]||'일정');const topHtml=top.map((x,k)=>`<article class="v13-date ${k===0?'best':''}"><div class="v13-rank">${k+1}순위</div><h3>${dayName(x.d)} <span>${hour(x.tw.a,x.tw.b)}</span></h3><p><b>날짜를 이렇게 본 이유</b><br>${reasonDate(x,i)}</p><p><b>시간까지 이 구간을 고른 이유</b><br>${reasonTime(x)}</p><p class="v13-use"><b>실제로 잡는다면</b><br>${scheduleExample(i,x)}</p></article>`).join('');return `<div class="v13-schedule"><span class="badge">${rg.label} ${intentName} 택일</span><div class="v13-best"><small>제가 하나만 고른다면</small><h2>${dayName(best.d)}<br>${hour(best.tw.a,best.tw.b)}</h2><p>${intentName}이라는 목적에 맞는 현실 시간대를 먼저 제한한 뒤, 그 안에서 내 원국과 일진·시주의 관계를 비교했습니다. 좋은 날 하나를 찍는 게 아니라 <b>후보 전체를 비교해서 가장 마찰이 적은 쪽</b>을 고른 겁니다.</p></div>${topHtml}${worst&&worst.ds!==best.ds?`<div class="v13-worst"><b>가능하면 뒤로 둘 후보</b><p>${dayName(worst.d)} ${hour(worst.tw.a,worst.tw.b)}는 다른 후보보다 일지·시지 관계에서 부담 신호가 더 많아 순위를 낮췄습니다. 꼭 이 날이어야 한다면 큰 결론보다 만남·확인까지만 가볍게 잡으세요.</p></div>`:''}<details><summary>전문 계산 근거</summary><p class="small">날짜마다 내 일주↔일진 합·충, 일간 관계, 목적별 전통력 宜/忌를 비교했습니다. 시간은 시주, 내 일지↔시지, 당일 일지↔시지, 시간 천간 관계를 따로 비교했습니다. 내부 비교값은 성공확률이 아닙니다.</p></details></div>`}
function scheduleExample(i,x){const t=hour(x.tw.a,x.tw.b);return ({소개팅:`${t}에 카페나 식사 한 곳만 잡으세요. 상대에게는 “${dayName(x.d)} ${x.tw.a}시쯤 괜찮아요?”처럼 확인하고, 너무 긴 코스는 미리 확정하지 않는 편이 좋습니다.`,데이트:`${t}에 만나 식사와 산책 정도로 여유를 두세요. 일정 사이에 이동을 많이 넣지 않는 편이 좋습니다.`,고백:`${t} 중에서도 만남 후반부, 둘이 충분히 이야기한 뒤 조용한 순간에 짧게 마음을 꺼내세요.`,약속:`${t}를 1안으로 제안하고 다른 후보 한 개를 2안으로 같이 보내세요.`,직장대화:`${t} 중 회의 직전·점심 직전은 피하고 20~30분 정도 따로 잡아 이야기하세요. 자료는 한 장으로 정리해 가면 좋습니다.`,면접지원:`가능하면 ${t} 중 앞쪽 시간을 고르고 15~20분 전에 도착하세요.`,계약:`${t} 안에서 상대에게 서명 전 최종 계약서를 다시 받아 읽을 시간을 확보하세요.`,이사:`${t}에 실제 작업을 시작하되 엘리베이터·관리사무소·잔금 일정이 맞는지 먼저 확인하세요.`,여행:`${t} 출발을 기준으로 교통 지연을 흡수할 여유 시간을 30~60분 남겨두세요.`}[i]||`${t}를 우선 후보로 쓰되 상대 일정과 실제 장소 조건이 맞는지 먼저 확인하세요.`)}

function answer13(){const p=prof();if(!p)return alert('내 사주를 먼저 등록하세요.');const q=$('#askText')?.value.trim();if(!q)return alert('질문을 입력하세요.');const out=$('#askResult');try{out.hidden=false;out.innerHTML=answer(q);out.scrollIntoView({behavior:'smooth',block:'start'})}catch(e){out.hidden=false;out.innerHTML=`<p>${e.message||'상담 계산 중 오류가 발생했습니다.'}</p>`}}
function enhanceProfile(){const result=$('#profileResult');if(!result||result.hidden||$('#v13-counsel-note'))return;const c=ctx();if(!c)return;const div=document.createElement('div');div.id='v13-counsel-note';div.className='v13-profile-note';div.innerHTML=`<h3>사주를 읽을 때 이렇게 보세요</h3><p>숫자와 용어를 따로 외우기보다 <b>원국은 내 기본 성향</b>, <b>대운은 10년짜리 배경</b>, <b>세운은 그 해의 주제</b>, <b>월운은 실제로 움직일 시기</b>라고 생각하면 쉽습니다. 아래 설명도 “좋다/나쁘다”보다 <b>어떤 상황에서 어떤 선택을 하면 내 구조를 잘 쓰는가</b>를 중심으로 읽어보세요.</p>`;result.insertBefore(div,result.firstChild)}
function ui(){const note=$('#v12-note');if(note){note.innerHTML='<b>13.0 실전 상담가 엔진</b><span>같은 말을 되풀이하지 않고, 질문의 실제 상황에 맞춰 사례·대화문·조건을 바꿔 설명합니다. “언제?”라고 물으면 날짜와 시간까지 비교합니다.</span>'}const btn=$('#askBtn');if(btn){btn.onclick=answer13;btn.textContent='상담하듯 자세히 풀어보기'}const more=$('#more .stack.small');if(more){const first=more.querySelector('div');if(first)first.innerHTML='<b>버전</b> 13.0 · 실전 상담가 엔진'}document.title='오늘결 13.0 · 실전 사주상담';try{enhanceProfile()}catch{}}
const old=window.renderProfile||window.renderProfile; if(typeof old==='function'){window.renderProfile=function(){old();setTimeout(enhanceProfile,0)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ui);else ui();
window.answer13=answer13;
})();
