// 사주톡톡 15.0 · 현장상담형 대화 엔진
(()=>{
'use strict';
const q=s=>document.querySelector(s);
const STORE='todaygyeol.v2.profile';
const HIST='sajutalk.v15.history';
const WEEK=['일','월','화','수','목','금','토'];
const pad=n=>String(n).padStart(2,'0');
function prof(){try{return JSON.parse(localStorage.getItem(STORE)||'null')}catch{return null}}
function hist(){try{return JSON.parse(localStorage.getItem(HIST)||'[]')}catch{return[]}}
function remember(x){const h=hist();h.push(String(x));localStorage.setItem(HIST,JSON.stringify(h.slice(-80)))}
function norm(x){return String(x||'').replace(/\s+/g,'').replace(/[.,!?~·•:;()\[\]"']/g,'')}
function sim(a,b){a=norm(a);b=norm(b);if(!a||!b)return 0;const A=new Set([...a]),B=new Set([...b]);let n=0;A.forEach(v=>B.has(v)&&n++);return n/Math.max(A.size,B.size)}
function choose(arr,key=''){if(!arr?.length)return'';let seed=0;for(const ch of key)seed=(seed*33+ch.charCodeAt(0))>>>0;const h=hist().slice(-20);for(let i=0;i<arr.length;i++){const x=arr[(seed+i)%arr.length];if(!h.some(v=>sim(v,x)>.72)){remember(x);return x}}return arr[seed%arr.length]}
function ctx(){try{const p=prof();if(!p)return null;const ec=ecFromSolar(solarFromProfile(p),p);const cnt=countElements(ec,p);const ord=Object.entries(cnt).sort((a,b)=>b[1]-a[1]);return{p,ec,gan:ec.getDayGan(),zhi:ec.getDayZhi(),dm:DAYMASTER?.[ec.getDayGan()]||{},high:ord[0]?.[0]||'',low:ord.at(-1)?.[0]||'',cnt}}catch{return null}}
function diToday(){try{return dayInfo(todayYmd(),prof())}catch{return null}}
function ganko(x){try{return ganzhiKo(x)}catch{return x||''}}
function actor(qs){if(/팀장|상사|부장|과장|대표/.test(qs))return'상사';if(/동료|직장동료|팀원/.test(qs))return'동료';if(/소개팅|소개받/.test(qs))return'소개팅 상대';if(/남친|여친|연인|애인/.test(qs))return'연인';if(/좋아하는|썸|호감/.test(qs))return'호감 있는 사람';if(/부모|엄마|아빠/.test(qs))return'부모';if(/친구/.test(qs))return'친구';return'상대';}
function intent(qs){
 const R=[['소개팅',/소개팅|소개\s*받/],['고백',/고백|사귀자|좋아한다고/],['데이트',/데이트|둘이\s*만나/],['재회',/재회|전남친|전여친|다시\s*만나/],['연락',/연락|카톡|문자|전화|디엠|DM/],['화해',/화해|사과|미안|서운|싸웠|갈등/],['호의',/간식|과자|커피|음료|밥\s*사|선물|챙겨/],['이직',/이직|퇴사|사표|회사\s*옮|직장\s*옮/],['승진',/승진|연봉|협상|고과|평가/],['면접',/면접|취업|입사지원|지원서/],['직장대화',/팀장|상사|부장|과장|업무|보고|회의|프로젝트/],['계약',/계약|서명|거래|임대차|전세|월세/],['투자',/주식|코인|투자|매수|매도|ETF|펀드/],['구매',/차\s*(살|사)|집\s*(살|사)|큰\s*돈|구매/],['창업',/창업|사업|가게|동업/],['시험',/시험|공부|자격증|수능|공시/],['가족',/부모|엄마|아빠|가족|자녀|아이|형제|자매/],['이사',/이사|입주|전입/],['여행',/여행|출장|출발|비행/],['건강',/병원|수술|치료|검사|약|건강|통증|아프/],['중요대화',/중요한\s*(말|이야기|얘기)|말\s*꺼|대화|설득|부탁/],['약속',/약속|만날까|만남|시간\s*잡/]];
 for(const [n,r] of R)if(r.test(qs))return n;return'일반';
}
function whenQ(qs){return /언제|몇\s*시|시간대|이번\s*주|다음\s*주|주말|이번\s*달|다음\s*달|날짜|요일/.test(qs)}
function risky(i){return ['투자','건강'].includes(i)}
const ADVICE={
 소개팅:{head:['잡아도 됩니다. 첫 만남은 짧게 보세요.','만나보는 쪽이 낫습니다. 하루 종일 코스는 빼세요.'],do:['식사나 카페 한 곳만 정하고 1~2시간 정도로 끝낼 수 있게 잡으세요. 첫 만남은 “얼마나 오래 있었나”보다 “다음에 또 보고 싶은가”가 더 중요합니다.','“언제 돼요?”보다 “금요일 저녁이나 토요일 오후 중 어느 쪽이 편해요?”처럼 두 선택지를 주세요. 상대가 답하기 쉬워집니다.'],script:['“토요일 5시쯤 괜찮아요? 너무 길게 잡지 말고 저녁이나 커피 정도 해요.”','“이번 주는 금요일 저녁이랑 토요일 오후가 괜찮은데, 편한 쪽 있어요?”'],branch:['상대가 야근이 잦다면 명리상 1순위여도 평일 늦은 시간은 빼는 게 낫습니다.','상대가 답을 계속 미룬다면 날짜를 더 찾기보다 만날 의향 자체부터 확인하세요.']},
 고백:{head:['말은 해도 됩니다. 답을 그 자리에서 재촉하지 마세요.','마음을 꺼내되 관계의 결론까지 한 번에 요구하지는 마세요.'],do:['긴 고백문보다 두 문장이 낫습니다. 내 마음을 말하고, 상대 생각을 물어보세요.','둘이 따로 만나는 게 자연스럽고 상대도 먼저 연락하거나 시간을 내는지 먼저 보세요. 이 신호가 날짜보다 중요합니다.'],script:['“나는 요즘 너를 친구 이상으로 생각해. 너는 우리를 어떻게 느껴?”','“너랑 둘이 만나는 시간이 좋은데, 나는 조금 더 진지하게 만나보고 싶어.”'],branch:['최근 답장이 짧아지고 약속을 계속 미룬다면 고백으로 분위기를 뒤집으려 하지 않는 편이 낫습니다.','상대가 먼저 시간을 만들고 개인적인 이야기를 자주 꺼낸다면 너무 오래 끌 필요도 없습니다.']},
 연락:{head:['한 번은 보내세요. 그리고 기다리세요.','연락해도 됩니다. 장문은 필요 없습니다.'],do:['안부 한 문장과 질문 하나면 충분합니다. 답이 없다고 같은 날 추가 메시지를 여러 번 보내지는 마세요.','오랜만이면 연락한 이유를 한 줄 넣으세요. 뜬금없는 “뭐해?”보다 훨씬 자연스럽습니다.'],script:['“지난번에 네가 말한 ○○ 생각나서. 요즘은 어때?”','“오늘 문득 생각났어. 이번 주는 좀 여유 있어?”'],branch:['답장이 늦어도 내용이 길고 질문이 돌아오면 관계 온도는 나쁘지 않습니다. 속도만 보지 마세요.','계속 단답이고 질문이 돌아오지 않는다면 연락 횟수를 늘리기보다 거리를 두는 편이 낫습니다.']},
 화해:{head:['풀어보세요. 다만 한 사건만 이야기하세요.','말은 꺼내되 과거 일을 전부 끌고 오지 마세요.'],do:['사실, 내 감정, 다음에 바라는 행동 순서로 말하면 됩니다. 사람 자체를 평가하지 마세요.','사과할 때 “그럴 의도는 아니었어”부터 붙이면 상대는 변명으로 듣기 쉽습니다. 먼저 상처가 된 부분을 인정하세요.'],script:['“어제 약속이 바뀌었는데 연락이 늦어서 서운했어. 다음에는 먼저 알려줬으면 해.”','“내가 그 말은 너무 세게 했어. 그 부분은 미안해. 다음엔 감정 올라왔을 때 바로 몰아붙이지 않을게.”'],branch:['둘 중 한 사람이 아직 목소리가 커질 만큼 화가 났다면 오늘은 결론보다 다음 대화 시간을 잡는 데까지만 가세요.','메신저로 오해가 커진 일이라면 장문 문자보다 짧게 만나서 푸는 편이 낫습니다.']},
 호의:{head:['하세요. 대신 작게 하세요.','가볍게 건네는 건 괜찮습니다. 부담스럽게 만들지만 마세요.'],do:['선물처럼 포장하기보다 “같이 드실래요?” 정도로 공동 간식처럼 꺼내세요.','상대가 바쁜 순간이면 간식만 건네고 나오세요. 대화는 상대가 이어올 때 붙이는 편이 자연스럽습니다.'],script:['“저도 먹으려고 샀는데 같이 드실래요?”','“커피 드세요? 하나 사려는데 같이 주문할까요?”'],branch:['아직 별로 친하지 않다면 비싼 것보다 작은 간식이 낫습니다.','상대가 이미 여러 번 부담스러워했다면 호의를 늘리는 것보다 거리를 존중하는 쪽이 맞습니다.']},
 직장대화:{head:['말하세요. 대신 결정받을 내용을 들고 가세요.','상사에게 이야기할 수 있습니다. “힘들다”보다 “무엇을 정해 달라”가 보여야 합니다.'],do:['메모는 세 줄이면 됩니다. 현재 상황, 문제가 되는 부분, 원하는 결정. 이 순서로 말하세요.','업무량 이야기라면 일정 충돌을 숫자로 보여주세요. 그러면 감정 호소가 아니라 업무 판단이 됩니다.'],script:['“A와 B 마감이 이번 주에 겹칩니다. A를 먼저 하면 B가 금요일까지 늦어집니다. 어느 쪽을 우선할까요?”','“현재 세 업무가 동시에 들어와 있습니다. 이번 주 기준 우선순위를 정해주시면 그 순서대로 처리하겠습니다.”'],branch:['상사가 급한 보고를 받는 중이면 좋은 시간이어도 끼어들지 마세요. 20분을 따로 잡는 편이 낫습니다.','평가나 연봉 이야기라면 느낌보다 매출, 시간 단축, 오류 감소처럼 숫자로 남은 결과 2~3개를 가져가세요.']},
 이직:{head:['옮길 수는 있습니다. 퇴사부터 하지 마세요.','이직을 볼 때는 운보다 오퍼 조건표가 먼저입니다.'],do:['연봉, 실제 역할, 상사, 근무시간, 출퇴근, 2년 뒤 경력가치를 현재 회사와 같은 표에 놓고 비교하세요.','오퍼레터가 확정되기 전 사표부터 내는 건 피하세요. 좋은 흐름이어도 문서가 없으면 아직 결정 단계가 아닙니다.'],script:['“연봉은 올랐는데 업무 범위와 출퇴근까지 포함하면 실제로 좋아지는 게 맞나?”를 표로 확인하세요.','면접에서 꼭 물어볼 건 “입사 후 6개월 안에 기대하는 결과가 무엇인지”입니다. 직무의 실제 모습을 알기 좋습니다.'],branch:['연봉이 10% 올라도 하루 출퇴근이 2시간 늘고 경력에 남는 일이 줄면 체감 조건은 나빠질 수 있습니다.','연봉 차이가 작아도 책임 범위와 성장성이 커진다면 장기적으로는 더 좋은 이동이 될 수 있습니다.']},
 승진:{head:['말할 때는 숫자 세 개를 준비하세요.','협상은 가능합니다. 성과를 문장보다 숫자로 보여주세요.'],do:['최근 6~12개월에서 비용을 줄인 일, 시간을 줄인 일, 책임이 커진 일 가운데 세 가지를 정리하세요.','원하는 조건을 최소, 목표, 대안 세 단계로 준비하세요. 그래야 한 번 거절돼도 다음 수가 있습니다.'],script:['“재구매율을 18%에서 25%로 올렸고, 월 마감 시간을 이틀 줄였습니다.”처럼 말하세요.','“현재 역할 범위가 입사 당시보다 넓어졌는데, 이 부분을 직급과 보상에 어떻게 반영할 수 있을까요?”'],branch:['직함만 올라가고 권한과 보상은 그대로인데 책임만 늘어난다면 승진 자체가 좋은 조건인지 다시 봐야 합니다.','성과 근거가 아직 약하면 이번에는 협상보다 다음 평가까지 무엇을 만들지 합의하는 편이 낫습니다.']},
 면접:{head:['지원하세요. 사례 세 개만 제대로 준비하세요.','좋은 날보다 답할 사례가 준비됐는지가 더 중요합니다.'],do:['성공 사례 2개와 실패 후 고친 사례 1개를 상황, 행동, 결과 순서로 40초 안에 말할 수 있게 준비하세요.','“협업을 잘합니다”라고 말하지 말고 협업으로 실제 무엇을 해결했는지 이야기하세요.'],script:['“개발과 영업 일정이 충돌했을 때 우선순위 표를 만들어 지연을 2주에서 3일로 줄였습니다.”처럼 말하면 그림이 보입니다.','마지막 질문에는 “이 역할에서 입사 6개월 뒤 잘하고 있다고 판단하는 기준은 무엇인가요?”를 물어보세요.'],branch:['경력 전환 면접이면 왜 바꾸는지만 말하지 말고 기존 경험 중 새 직무에 그대로 가져갈 능력을 연결하세요.','면접 시간이 좋더라도 준비가 덜 됐다면 하루 연기가 가능한지 현실적으로 보는 게 낫습니다.']},
 계약:{head:['날은 참고만 하세요. 계약서는 실제로 읽어야 합니다.','서명은 조건 확인이 끝났을 때만 하세요.'],do:['금액, 기간, 해지, 위약금, 자동갱신, 책임범위를 먼저 보세요. 구두로 합의한 내용은 문서에 없으면 없는 것으로 생각하는 편이 안전합니다.','계약서에서 내가 가장 불리해질 수 있는 상황을 하나 상상하고, 그때 조항이 어떻게 작동하는지 확인하세요.'],script:['“중도해지할 때 비용은 얼마고, 자동연장은 언제 취소해야 하나요?”를 먼저 물어보세요.','사업 계약이면 지급일, 검수 기준, 수정 횟수, 지연 책임을 문장으로 남기세요.'],branch:['상대가 “오늘 안 하면 조건이 사라진다”고 압박하면 좋은 날이어도 바로 서명하지 않는 편이 낫습니다.','계약금이 큰 경우에는 사주보다 전문가 검토 비용이 훨씬 싸게 먹힐 수 있습니다.']},
 투자:{head:['사주로 매수·매도 시점을 정하지 마세요.','운보다 손실 한도와 투자 근거를 먼저 보세요.'],do:['왜 사는지, 얼마까지 잃을 수 있는지, 언제 판단이 틀렸다고 인정할지 세 가지가 없으면 아직 투자 결정이 아닙니다.','생활비와 비상금을 건드리지 않는 범위인지 먼저 확인하세요.'],script:['“이 가격에 사는 이유가 실적·가치 때문인지, 그냥 오르는 걸 보고 따라가는 건지”부터 적어보세요.','한 번의 운세 결과 때문에 투자 비중을 늘리지는 마세요.'],branch:['급등 뒤 따라가는 상황이라면 명리보다 가격과 리스크를 먼저 보세요.','대출이나 생활비까지 써야 한다면 운세와 관계없이 규모를 줄이는 게 맞습니다.']},
 구매:{head:['살 수 있는지 말고, 사고 나서도 편한지 보세요.','큰돈은 오늘 기분보다 1년 총비용으로 판단하세요.'],do:['차라면 할부, 보험, 세금, 주차, 유지비까지 합치고 집이라면 이자, 관리비, 세금, 수리비까지 보세요.','사고 나서 생활비와 비상금이 흔들리지 않는지가 기준입니다.'],script:['“월 납입금” 말고 “1년에 실제로 빠져나가는 총액”을 계산하세요.','집이라면 금리가 1~2%p 올라가도 버틸 수 있는지 같이 계산하세요.'],branch:['예산 안에 들어와도 유지비가 예상보다 크면 체감 부담은 전혀 달라집니다.','큰 구매를 스트레스 해소용으로 하고 있다면 하루 이틀 미루고 다시 보는 편이 낫습니다.']},
 창업:{head:['계약보다 작은 판매 테스트부터 하세요.','사업운보다 고객이 실제로 돈을 내는지 먼저 확인하세요.'],do:['가게를 얻기 전에 실제 고객 10명에게 유료로 팔아보세요. 반응이 없으면 인테리어보다 상품을 먼저 고쳐야 합니다.','동업이라면 지분, 역할, 급여, 추가자금, 그만둘 때 정산 방식을 문서로 정하세요.'],script:['카페라면 객단가와 월 고정비를 놓고 하루 몇 명이 와야 버티는지 먼저 계산하세요.','온라인이라면 소액 광고로 문의와 구매전환부터 확인한 뒤 규모를 키우세요.'],branch:['“좋은 상권”이라는 말보다 실제 유동인구와 경쟁점 매출 추정이 더 중요합니다.','동업자가 친한 사람이라는 이유로 역할과 돈 문제를 문서화하지 않으면 나중에 관계가 더 힘들어질 수 있습니다.']},
 시험:{head:['새 범위를 넓히기보다 약점을 줄이세요.','오늘은 공부시간보다 오답 이유를 보는 편이 낫습니다.'],do:['틀린 문제를 몰라서, 헷갈려서, 시간 부족으로 나눠보세요. 다음 행동이 바로 보입니다.','시험이 가까우면 새 교재보다 이미 본 자료를 다시 보는 편이 효율적입니다.'],script:['2시간이면 60분 문제풀이, 40분 오답, 20분 암기 확인처럼 목적을 나누세요.','모의고사 총점보다 과목별 시간 사용을 먼저 확인해보세요.'],branch:['기본 개념이 비어 있다면 문제 수를 늘리는 것보다 그 단원 하나를 다시 보는 편이 낫습니다.','불안해서 교재만 계속 바꾸는 시기라면 지금 가진 자료 하나를 끝내는 게 낫습니다.']},
 이사:{head:['날짜는 고를 수 있습니다. 현실 일정이 비슷한 후보끼리 비교하세요.','명리상 좋은 날보다 잔금과 실제 입주가 가능한 날이 먼저입니다.'],do:['엘리베이터 예약, 잔금, 열쇠 인수, 인터넷 설치, 이사업체 시간을 먼저 맞추고 그중에서 좋은 날을 고르세요.','비용 차이가 큰 경우에는 1순위 길일을 고집하지 말고 현실적으로 가능한 2순위를 쓰는 편이 낫습니다.'],script:['“잔금 송금 9시, 열쇠 인수 10시, 이삿짐 10시30분”처럼 실제 시간표를 먼저 잡으세요.','토요일 비용이 두 배라면 평일 2순위가 오히려 만족도가 높을 수 있습니다.'],branch:['출생시간이 시주 경계에 가깝다면 시간 택일은 더 보수적으로 보세요.','입주일과 실제 이사일이 다르면 어느 날짜를 기준으로 볼지 먼저 정해야 합니다.']},
 여행:{head:['가도 됩니다. 동선에 여유를 두세요.','좋은 날보다 지연을 흡수할 시간이 있는 일정이 좋습니다.'],do:['공항이나 역 도착시간을 너무 딱 맞추지 말고 30~60분 여유를 남기세요.','첫날 일정은 하나 줄이는 편이 좋습니다. 이동이 길면 컨디션이 여행 전체를 좌우합니다.'],script:['환승이 두 번 이상이면 최저가보다 환승시간과 지연 대안을 먼저 보세요.','출장이면 중요한 미팅 당일 이동보다 하루 전 이동이 가능한지 확인하세요.'],branch:['날씨나 교통 변수가 큰 여행은 길일보다 취소·변경 가능한 예약이 더 중요합니다.','동행자가 피곤한 일정이라면 내 운이 좋아도 전체 만족도는 떨어질 수 있습니다.']},
 건강:{head:['사주는 참고만 하세요. 증상은 의료진이 봐야 합니다.'],do:['통증, 출혈, 호흡곤란, 의식 변화처럼 실제 증상이 있으면 운세보다 진료가 먼저입니다.','생활 쪽에서는 수면, 식사, 음주, 운동, 회복 시간을 기록하는 정도로 활용하세요.'],script:['검사 결과를 기다리는 상황이라면 사주로 결과를 예측하지 말고 의사의 설명과 추가검사 계획을 확인하세요.'],branch:['증상이 갑자기 심해졌다면 날짜를 고르지 말고 바로 의료기관에 연락하는 게 맞습니다.']},
 중요대화:{head:['말하세요. 핵심 하나만 꺼내세요.','대화는 가능합니다. 결론을 한 번에 다 받으려 하지는 마세요.'],do:['상대가 대답할 수 있는 질문 하나로 끝내세요. 설명이 길어지면 핵심이 흐려집니다.','돈, 관계, 업무가 한꺼번에 섞여 있다면 가장 급한 하나만 먼저 다루세요.'],script:['“지난 두 번 약속이 취소됐는데 앞으로 만날 의향이 있는지 알고 싶어.”처럼 구체적으로 묻는 편이 낫습니다.','“제가 원하는 건 사과보다 다음부터 어떻게 할지 정하는 겁니다.”라고 말하면 대화가 덜 퍼집니다.'],branch:['상대가 이미 방어적으로 올라와 있다면 오늘은 결론보다 다음 대화 시간을 잡는 데까지만 가세요.','문제로만 말하지 말고 원하는 행동 하나를 같이 말해야 상대도 답하기 쉽습니다.']},
 약속:{head:['잡아도 됩니다. 두 시간대를 제시하세요.','약속은 상대가 고르기 쉽게 잡으세요.'],do:['“언제 돼?”보다 두 후보를 주는 게 낫습니다. 첫 약속이면 취소·변경이 쉬운 장소를 잡으세요.','멀리 이동해야 하는 약속은 퇴근 직후보다 주말 오후가 실제 만족도가 높을 수 있습니다.'],script:['“금요일 7시나 토요일 4시 중 어느 쪽이 편해?”','“이번 주는 토요일 오후가 제일 편한데, 4시쯤 어때?”'],branch:['상대가 교대근무라면 먼저 쉬는 날을 받은 뒤 그 안에서 시간을 고르세요.','상대가 계속 선택을 미루면 날짜 문제라기보다 우선순위 문제일 수 있습니다.']},
 일반:{head:['작게 먼저 해보세요. 반응을 보고 다음 수를 정하면 됩니다.'],do:['되돌리기 쉬운 행동부터 시작하세요. 큰 결정은 정보가 더 모인 뒤 해도 늦지 않습니다.'],script:['말이라면 한 문장만, 돈이라면 작은 금액만, 관계라면 짧은 만남 한 번만 먼저 해보세요.'],branch:['한 번 해보고 반응이 예상과 다르면 그때 방향을 바꾸면 됩니다.']}
};
function natalLine(c,i,a){if(!c)return'';const t=c.dm?.traits||[];const trait=t[(i.length+a.length)%Math.max(1,t.length)]||'';const high=c.high?`${c.high} 기운이 상대적으로 강하고`:'';const low=c.low?`${c.low} 기운은 보완이 필요한 편이라`:'';const map={
 소개팅:'첫인상에서 너무 많은 걸 보여주기보다 상대 반응을 보며 속도를 맞추는 쪽이 좋습니다.',고백:'마음이 정해져도 상대의 답을 기다릴 자리를 남기는 게 중요합니다.',연락:'생각이 길어지기 전에 짧게 보내고 상대 반응을 보는 편이 낫습니다.',직장대화:'혼자 해결하려 버티기보다 기준과 우선순위를 상대에게 확인하는 게 좋습니다.',이직:'가능성을 넓게 보되 실제 조건표로 좁혀야 판단이 선명해집니다.',승진:'내가 한 일을 상대가 알아서 알아주길 기다리기보다 성과를 보이게 정리해야 합니다.',화해:'옳고 그름보다 한 사건을 정확히 짚는 편이 관계를 풀기 쉽습니다.',호의:'정성을 크게 보이기보다 부담 없는 크기로 표현하는 게 좋습니다.'};
 return `${c.dm?.name||ganko(c.gan)}은 ${c.dm?.symbol||'자기 방식'}에 비유합니다. ${trait?trait+'이고, ':''}${high}${low} ${map[i]||'큰 결정보다 상황을 보며 한 단계씩 움직이는 편이 맞습니다.'}`;
}
function dayBasis(d){if(!d)return[];const arr=[];const natal=`내 일주 ${ganko(d.natal?.getDay?.()||'')}`;const day=`오늘 일진 ${ganko(d.ec?.getDay?.()||'')}`;if(d.inter?.type==='합')arr.push(`${natal}와 ${day}의 지지가 합으로 이어집니다. 관계·협의가 붙기 쉬운 신호로 봅니다.`);else if(d.inter?.type==='충')arr.push(`${natal}와 ${day}의 지지가 충입니다. 변화와 마찰이 커질 수 있어 한 번에 결론내기보다 나눠 가는 쪽이 낫습니다.`);else arr.push(`${natal}와 ${day} 사이에 큰 합·충은 없습니다. 이런 날은 실제 준비와 상대 상황의 비중을 더 크게 봅니다.`);
 const rm={지원:'오늘 천간 관계는 도움·정보를 받는 쪽입니다.',표현:'오늘 천간 관계는 말·제안·표현을 꺼내는 쪽입니다.',관리:'오늘 천간 관계는 돈·조건·약속을 정리하는 쪽입니다.',압박:'오늘 천간 관계는 책임과 압박이 커질 수 있어 서두르지 않는 편이 좋습니다.',동질:'오늘 천간 관계는 내 방식대로 밀기 쉬워 상대 속도를 확인하는 게 중요합니다.'};if(rm[d.rel])arr.push(rm[d.rel]);return arr;
}
function answer(qs){const c=ctx(),d=diToday(),i=intent(qs),a=actor(qs),A=ADVICE[i]||ADVICE.일반,k=qs+(c?.gan||'')+(d?.ec?.getDay?.()||'');const head=choose(A.head,k+'h'),body=choose(A.do,k+'d'),script=choose(A.script,k+'s'),branch=choose(A.branch,k+'b');const nline=natalLine(c,i,a);const basis=dayBasis(d);const risk=risky(i);
 let html=`<div class="v15-consult"><div class="v15-label">${i==='일반'?'상담':i}</div><h2>${head}</h2><p class="v15-lead">${body}</p>`;
 if(script)html+=`<div class="v15-scene"><b>실제로는 이렇게</b><p>${script}</p></div>`;
 if(branch)html+=`<div class="v15-if"><b>이 경우엔 다르게 봅니다</b><p>${branch}</p></div>`;
 if(nline)html+=`<div class="v15-person"><b>${c?.p?.name||'당신'} 사주에서는</b><p>${nline}</p></div>`;
 if(risk)html+=`<div class="v15-warning">${i==='투자'?'투자 결정은 가격·재무·손실한도·자산배분을 우선하세요.':'증상과 검사 결과는 의료진의 판단을 우선하세요.'}</div>`;
 html+=`<details class="v15-basis"><summary>왜 이렇게 보나요?</summary>${basis.map(x=>`<p>• ${x}</p>`).join('')}<p class="tiny">사주는 전통 명리 해석의 참고자료이며 결과를 보장하는 예측이 아닙니다.</p></details></div>`;return html;}
function range(qs){const n=new Date();n.setHours(0,0,0,0);let s=new Date(n),e=new Date(n),label='이번 주',dow=n.getDay();if(/다음\s*주/.test(qs)){const add=(8-dow)%7||7;s.setDate(n.getDate()+add);e=new Date(s);e.setDate(s.getDate()+6);label='다음 주'}else if(/다음\s*주말/.test(qs)){const add=((6-dow+7)%7)+7;s.setDate(n.getDate()+add);e=new Date(s);e.setDate(s.getDate()+1);label='다음 주말'}else if(/주말/.test(qs)){const add=(6-dow+7)%7;s.setDate(n.getDate()+add);e=new Date(s);e.setDate(s.getDate()+1);label='이번 주말'}else if(/다음\s*달/.test(qs)){s=new Date(n.getFullYear(),n.getMonth()+1,1);e=new Date(n.getFullYear(),n.getMonth()+2,0);label='다음 달'}else if(/이번\s*달/.test(qs)){e=new Date(n.getFullYear(),n.getMonth()+1,0);label='이번 달'}else{e.setDate(n.getDate()+(7-dow));if(dow===0)e=new Date(n)}return{s,e,label}}
function purpose(i){if(['소개팅','데이트','고백','약속','재회'].includes(i))return'소개팅·만남';if(['계약','구매','창업'].includes(i))return'계약·거래';if(['이사','여행'].includes(i))return'이사·이동';if(['시험','면접'].includes(i))return'공부·시험 준비';return'중요한 대화'}
function windows(i){if(['소개팅','데이트','고백','약속','재회'].includes(i))return[[15,17],[17,19],[19,21]];if(['직장대화','승진','면접','계약'].includes(i))return[[9,11],[11,13],[13,15],[15,17]];if(['이사','여행'].includes(i))return[[7,9],[9,11],[11,13],[13,15]];return[[9,11],[11,13],[15,17],[17,19]]}
function timeScore(date,p,a,b){try{const sol=Solar.fromYmdHms(date.getFullYear(),date.getMonth()+1,date.getDate(),a,0,0),ec=sol.getLunar().getEightChar(),ne=ecFromSolar(solarFromProfile(p),p),ia=interaction(ne.getDayZhi(),ec.getTimeZhi()),ib=interaction(ec.getDayZhi(),ec.getTimeZhi()),r=relation(ne.getDayGan(),ec.getTimeGan());let sc=60+(ia.type==='합'?11:ia.type==='충'?-13:0)+(ib.type==='합'?5:ib.type==='충'?-6:0)+({지원:6,표현:5,관리:3,동질:2,압박:-5}[r]||0);return{sc,a,b,ia,ib,r,time:`${ec.getTimeGan()}${ec.getTimeZhi()}`}}catch{return{sc:0,a,b}}}
function schedule(qs){const p=prof();if(!p)return'<p>내 사주를 먼저 등록해주세요.</p>';if(typeof Solar==='undefined')return'<p>만세력 엔진을 불러온 뒤 다시 시도해주세요.</p>';const i=intent(qs),rg=range(qs),pu=purpose(i),ws=windows(i),rows=[];for(let x=new Date(rg.s);x<=rg.e;x.setDate(x.getDate()+1)){const ds=`${x.getFullYear()}-${pad(x.getMonth()+1)}-${pad(x.getDate())}`;try{const d=dayInfo(ds,p);let sc=purposeScore(d,pu),bt=null;for(const [a,b] of ws){const t=timeScore(x,p,a,b);if(!bt||t.sc>bt.sc)bt=t}sc+=Math.round(((bt?.sc||60)-60)*.4);rows.push({date:new Date(x),d,t:bt,sc})}catch{}}
 rows.sort((a,b)=>b.sc-a.sc);const top=rows.slice(0,3);if(!top.length)return'<p>날짜를 계산하지 못했습니다.</p>';const fmt=x=>`${x.date.getMonth()+1}월 ${x.date.getDate()}일 ${WEEK[x.date.getDay()]}요일`,tm=x=>`${pad(x.t.a)}:00~${pad(x.t.b)}:00`;function why(x){const a=[];if(x.d.inter?.type==='합')a.push('내 일지와 그날 일지가 합');else if(x.d.inter?.type==='충')a.push('내 일지와 그날 일지가 충이라 감점');else a.push('내 일지와 그날 일지에 큰 충이 없음');if(x.d.rel==='표현')a.push('그날 천간은 말·제안을 꺼내는 관계');else if(x.d.rel==='지원')a.push('그날 천간은 도움·정보를 받는 관계');else if(x.d.rel==='관리')a.push('조건·약속을 정리하는 관계');if(x.t?.ia?.type==='합')a.push('추천 시지가 내 일지와 합');else if(x.t?.ia?.type==='충')a.push('추천 시간의 충 요소가 있어 순위를 낮춤');return a.slice(0,3).join(' · ')}
 const first=top[0];let practical=i==='소개팅'?`${fmt(first)} ${first.t.a}시쯤 괜찮은지 먼저 물어보세요. 첫 만남은 식사나 카페 한 곳 정도로 짧게 잡는 게 좋습니다.`:i==='직장대화'?`${tm(first)} 안에서 회의 직전은 피하고 20~30분을 따로 잡으세요. 문제·영향·원하는 결정을 세 줄로 가져가면 됩니다.`:`${fmt(first)} ${tm(first)}를 1안으로 제시하고, 안 맞으면 바로 2순위를 제시하세요.`;
 return `<div class="v15-consult"><div class="v15-label">${rg.label} 택일</div><h2>${fmt(first)}<br><span>${tm(first)}</span></h2><p class="v15-lead">제가 하나만 고르면 이때입니다. ${why(first)}.</p><div class="v15-scene"><b>실제로는 이렇게</b><p>${practical}</p></div><div class="v15-ranks">${top.map((x,n)=>`<div><b>${n+1}순위 · ${fmt(x)}</b><span>${tm(x)}</span><small>${why(x)}</small></div>`).join('')}</div><details class="v15-basis"><summary>날짜와 시간 근거</summary><p>기간 안의 모든 후보를 비교해 내 일주와 그날 일진의 합·충, 일간 관계, 목적별 전통력 宜/忌, 추천 시간의 시주와 내 일지·당일 일지 관계를 함께 봤습니다.</p><p class="tiny">이 순위는 전통 명리 규칙 안에서의 상대 비교이며 성공확률을 뜻하지 않습니다.</p></details></div>`}
function run(){const input=q('#askText'),out=q('#askResult');const text=input?.value.trim();if(!text)return alert('궁금한 내용을 적어주세요.');out.hidden=false;out.innerHTML=whenQ(text)?schedule(text):answer(text);out.scrollIntoView({behavior:'smooth',block:'start'})}
function polish(){document.title='사주톡톡 · 쉽게 묻고 구체적으로 듣는 사주상담';const sub=q('.top .sub');if(sub)sub.textContent='어렵게 말하지 않고, 실제 상황으로 풀어드립니다';const ask=q('#ask');if(ask){const sh=ask.querySelector('.scene-head');if(sh){sh.querySelector('span').textContent='사주상담';sh.querySelector('strong').textContent='궁금한 걸 그대로 물어보세요';sh.querySelector('small').textContent='결론부터 말하고, 실제로 어떻게 할지까지 알려드립니다.'}const btn=q('#askBtn');if(btn){const b=btn.cloneNode(true);b.id='askBtn';b.textContent='바로 상담받기';btn.replaceWith(b);b.onclick=run}const quick=ask.querySelector('.quickchips');if(quick){quick.innerHTML='<button data-q="이번 주 소개팅은 언제가 좋아? 날짜와 시간도 알려줘">소개팅</button><button data-q="팀장에게 업무량 이야기를 어떻게 꺼내는 게 좋아?">직장</button><button data-q="요즘 이직 제안이 왔는데 옮기는 게 나을까?">이직</button><button data-q="좋아하는 사람에게 오늘 연락해도 될까?">연애</button>';quick.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{q('#askText').value=b.dataset.q})}}
 const more=q('#more .stack.small div');if(more)more.innerHTML='<b>버전</b> 15.0 · 현장상담형';
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',polish);else polish();
window.sajuTalk15Run=run;
})();
